var annotated_dup =
[
    [ "SINRICPRO_3_2_1", "namespace_s_i_n_r_i_c_p_r_o__3__2__1.html", [
      [ "SinricProClass", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_class.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_class" ],
      [ "SinricProAirQualitySensor", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_air_quality_sensor.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_air_quality_sensor" ],
      [ "SinricProBlinds", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_blinds.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_blinds" ],
      [ "SinricProCamera", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_camera.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_camera" ],
      [ "SinricProContactsensor", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_contactsensor.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_contactsensor" ],
      [ "SinricProDevice", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_device.html", null ],
      [ "SinricProDimSwitch", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_dim_switch.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_dim_switch" ],
      [ "SinricProDoorbell", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_doorbell.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_doorbell" ],
      [ "SinricProFan", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_fan.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_fan" ],
      [ "SinricProFanUS", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_fan_u_s.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_fan_u_s" ],
      [ "SinricProGarageDoor", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_garage_door.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_garage_door" ],
      [ "SinricProLight", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_light.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_light" ],
      [ "SinricProLock", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_lock.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_lock" ],
      [ "SinricProMotionsensor", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_motionsensor.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_motionsensor" ],
      [ "SinricProPowerSensor", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_power_sensor.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_power_sensor" ],
      [ "SinricProSpeaker", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_speaker.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_speaker" ],
      [ "SinricProSwitch", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_switch.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_switch" ],
      [ "SinricProTemperaturesensor", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_temperaturesensor.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_temperaturesensor" ],
      [ "SinricProThermostat", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_thermostat.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_thermostat" ],
      [ "SinricProTV", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_t_v.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_t_v" ],
      [ "SinricProWindowAC", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_window_a_c.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_window_a_c" ],
      [ "AirQualitySensor", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_air_quality_sensor.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_air_quality_sensor" ],
      [ "BrightnessController", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_brightness_controller.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_brightness_controller" ],
      [ "ChannelController", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_channel_controller.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_channel_controller" ],
      [ "ColorController", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_color_controller.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_color_controller" ],
      [ "ColorTemperatureController", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_color_temperature_controller.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_color_temperature_controller" ],
      [ "ContactSensor", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_contact_sensor.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_contact_sensor" ],
      [ "Doorbell", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_doorbell.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_doorbell" ],
      [ "DoorController", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_door_controller.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_door_controller" ],
      [ "EqualizerController", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_equalizer_controller.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_equalizer_controller" ],
      [ "InputController", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_input_controller.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_input_controller" ],
      [ "KeypadController", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_keypad_controller.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_keypad_controller" ],
      [ "LockController", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_lock_controller.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_lock_controller" ],
      [ "MediaController", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_media_controller.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_media_controller" ],
      [ "ModeController", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_mode_controller.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_mode_controller" ],
      [ "MotionSensor", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_motion_sensor.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_motion_sensor" ],
      [ "MuteController", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_mute_controller.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_mute_controller" ],
      [ "PercentageController", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_percentage_controller.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_percentage_controller" ],
      [ "PowerLevelController", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_power_level_controller.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_power_level_controller" ],
      [ "PowerSensor", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_power_sensor.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_power_sensor" ],
      [ "PowerStateController", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_power_state_controller.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_power_state_controller" ],
      [ "PushNotification", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_push_notification.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_push_notification" ],
      [ "RangeController", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_range_controller.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_range_controller" ],
      [ "TemperatureSensor", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_temperature_sensor.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_temperature_sensor" ],
      [ "ThermostatController", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_thermostat_controller.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_thermostat_controller" ],
      [ "ToggleController", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_toggle_controller.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_toggle_controller" ],
      [ "VolumeController", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_volume_controller.html", "class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_volume_controller" ]
    ] ]
];